# Generated by Django 3.0.4 on 2020-03-21 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ano', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='教工号')),
                ('name', models.CharField(max_length=25, verbose_name='管理员姓名')),
                ('password', models.CharField(max_length=25, verbose_name='密码')),
                ('phone', models.CharField(max_length=25, verbose_name='管理员电话')),
                ('desc', models.CharField(max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '管理员信息',
                'verbose_name_plural': '管理员信息',
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('bno', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='寝室楼号')),
                ('bsex', models.PositiveIntegerField(choices=[(0, '男寝'), (1, '女寝')], default=0, verbose_name='寝室类别')),
                ('desc', models.CharField(max_length=225, null=True, verbose_name='备注')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Admin', verbose_name='管理员')),
            ],
            options={
                'verbose_name': '寝室楼信息',
                'verbose_name_plural': '寝室楼信息',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('idCard', models.CharField(max_length=25, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=25, verbose_name='手机号')),
                ('sex', models.PositiveIntegerField(choices=0, default=0, verbose_name='性别')),
                ('birthday', models.DateTimeField(verbose_name='出生日期')),
                ('college', models.CharField(max_length=25, verbose_name='学院')),
                ('subject', models.CharField(max_length=25, verbose_name='专业')),
                ('grade', models.CharField(max_length=25, verbose_name='学院')),
                ('Class', models.CharField(max_length=25, verbose_name='班级')),
                ('room', models.CharField(max_length=10, verbose_name='寝室号')),
                ('session', models.CharField(max_length=255, null=True, verbose_name='Session')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Build', verbose_name='寝室楼号')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='In_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behave', models.PositiveIntegerField(choices=[(0, '出'), (1, '入')], default=0, verbose_name='出入情况')),
                ('reason', models.CharField(max_length=225, null=True, verbose_name='事由')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('temp', models.FloatField(verbose_name='体温')),
                ('sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='学生姓名')),
            ],
            options={
                'verbose_name': '学生登记信息',
                'verbose_name_plural': '学生登记信息',
            },
        ),
    ]
