# Generated by Django 3.0.4 on 2020-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200321_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_out',
            name='build',
            field=models.CharField(default=1, max_length=10, verbose_name='楼号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_out',
            name='college',
            field=models.CharField(default=1, max_length=25, verbose_name='学院'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_out',
            name='room',
            field=models.CharField(default=1, max_length=10, verbose_name='寝室号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='in_out',
            name='behave',
            field=models.PositiveIntegerField(choices=[(0, '出'), (1, '入')], default=1, verbose_name='出入情况'),
        ),
    ]
