# Generated by Django 3.0.4 on 2020-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200324_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_out',
            name='build_room',
            field=models.CharField(default=1, max_length=10, verbose_name='楼和寝室'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_out',
            name='subject_class',
            field=models.CharField(default=1, max_length=25, verbose_name='专业班级'),
            preserve_default=False,
        ),
    ]
