# Generated by Django 3.0.4 on 2020-03-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200324_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_out',
            name='build_room',
        ),
    ]
