# Generated by Django 3.0.4 on 2020-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_in_out_build_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_out',
            name='build',
        ),
        migrations.RemoveField(
            model_name='in_out',
            name='room',
        ),
        migrations.AddField(
            model_name='in_out',
            name='build_room',
            field=models.CharField(default=1, max_length=10, verbose_name='楼和寝室'),
            preserve_default=False,
        ),
    ]
