# Generated by Django 3.0.4 on 2020-03-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200324_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_out',
            name='build_room',
        ),
        migrations.AddField(
            model_name='in_out',
            name='build',
            field=models.CharField(default=1, max_length=10, verbose_name='寝室楼号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_out',
            name='room',
            field=models.CharField(default=1, max_length=10, verbose_name='寝室号'),
            preserve_default=False,
        ),
    ]
